<?php
//PHP and JSON to using the social count api.
function social_counter_processor(&$variables) {
    
    $variables['link'] = "http://tools.mercenie.com/social-share-count/api/?flag=15&format=json&url=".$variables['url'];
    $variables['contents'] = file_get_contents($variables['link']);
    $variables['jsons'] = json_decode($variables['contents']);
  return $variables['jsons'];
}
//sum of social counter
function social_counter_calculate(&$variables) {
    
    $variables['url'] = $_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];//define url
	$variables['counts'] = social_counter_processor($variables); //extend variable from function social_counter_processor
	$variables['fb_num'] = $variables['counts']->facebook->like_count;//fb like
	$variables['fb_nums'] = $variables['counts']->facebook->share_count;//fb share
	$variables['fball_num'] = $variables['counts']->facebook->total_count;//all of facebook
	$variables['twitter_num'] = $variables['counts']->twitter->count;//twitter
	$variables['gplus_num'] = $variables['counts']->google->plusone; // gplus
	$variables['total_num'] = $variables['fball_num'] + $variables['twitter_num'] + $variables['gplus_num']; //sum of all social media;
}

function social_counter_checker(&$variables) {
    
    $variables['counter_all'] = social_counter_calculate($variables); //extend variable from social_counter_calculate
    if ($variables['total_num'] == '0'){ // check if variable = 0
    	return $variables['total_num'] = '';
    }
}

//hook_preprocess_node() and set variable to node.tpl.php
function social_counter_preprocess_node(&$variables) {
   $variables['counter_all'] = social_counter_checker($variables); 	//extend variable from social_counter_checker 

   //Usage print $total_num; on your node.tpl.php 
}